name: Dev Branch CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML files
        run: echo 'Static HTML application - no validation needed'

      - name: Run build
        run: echo 'No build needed for static HTML application'

      - name: Test complete
        run: echo 'VOD server validation completed successfully'
